assert( Encrypt("ABCDEFGHIJKLMNOPQRSTUVWXYZ_", "EFGHIJKLMNOPQRSTUVWXYZ_ABCD", "HELLO") == "LIPPS",  'Should encrypt "HELLO" with setting=4 to "LIPPS"', "logic");

assert( Encrypt("ABCDEFGHIJKLMNOPQRSTUVWXYZ_", "PQRSTUVWXYZ_ABCDEFGHIJKLMNO", "ENCRYPTION_TEST") == "TBRFMDHXCBOHTGH",  'Should encrypt "ENCRYPTION_TEST" with setting=15 to "TBRFMDHXCBOHTGH"', "logic");

assert( Decrypt("ABCDEFGHIJKLMNOPQRSTUVWXYZ_", "EFGHIJKLMNOPQRSTUVWXYZ_ABCD", "LIPPS") == "HELLO",  'Should decrypt "LIPPS" with setting=4 to "HELLO"', "logic");

assert( Decrypt("ABCDEFGHIJKLMNOPQRSTUVWXYZ_", "PQRSTUVWXYZ_ABCDEFGHIJKLMNO", "TBRFMDHXCBOHTGH") == "ENCRYPTION_TEST",  'Should decrypt "TBRFMDHXCBOHTGH" with setting=15 to "ENCRYPTION_TEST"', "logic");

